# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-redevops-terraform-state"
    dynamodb_table = "dev-redevops-terraform-lock-table"
    encrypt        = true
    key            = "db/terraform.tfstate"
    profile        = "terraform-dev"
    region         = "us-east-2"
  }
}
